Add support to external mappings
mercurymedia/beetle_etl pull request #1
Opened 2020-01-17 10:21 UTC by gouvermxt

2020-01-17 10:23 UTC, gouvermxt commented
@Tranquility You will notice that some changes were made by Rubocop formatter that was turned on.

2020-01-17 15:23 UTC, Tranquility requested changes

2020-01-17 15:23 UTC, Tranquility commented on Dockerfile
> +WORKDIR /home/mercury/app
No need to use mercury you should be able to just do:

```
COPY Gemfile .
COPY Gemfile.lock .
COPY beetle_etl.gemspec .
```

2020-01-17 15:23 UTC, Tranquility commented on docker-compose.yml
> +    command: tail -f /dev/null
I don't think you need to have it running all the time. You can just call `rspec` here and execute the command whenever you want to run the tests.

2020-01-17 15:23 UTC, Tranquility commented on docker-compose.yml
> +      - .:/home/mercury/app
```suggestion
      - .:.
```

2020-01-17 15:23 UTC, Tranquility commented on lib/beetle_etl/steps/table_diff.rb
> +            mapping.external_id = target.external_id
shouldn't this be `stage` instead of `target`?

2020-01-23 09:07 UTC, Tranquility requested changes

2020-01-23 09:07 UTC, Tranquility commented on lib/beetle_etl/steps/step.rb
> +    def mapped_column_name(table_name = nil)
The name should communicate better what this is. Maybe something like `mapped_foreign_key_column`.

2020-01-23 09:07 UTC, Tranquility commented on beetle_etl.gemspec
> +  spec.version       = '2.0.4'
I am still wondering why you need this. And it probably should be 3.00.

2020-01-23 09:07 UTC, Tranquility commented on spec/support/database.yml.example
> -adapter: 'postgres'
Why did you remove this file?

2020-01-23 11:44 UTC, gouvermxt commented on spec/support/database.yml.example
> -adapter: 'postgres'
I renamed it to database.yml

2020-01-23 13:01 UTC, Tranquility approved these changes
LGTM

2020-11-11 14:34 UTC, gouvermxt commented
Duplicated.

2020-11-11 14:34 UTC, closed without merging